inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    # Templates are really ERB which Rubocop does not parse
    - bin/**/*
    - bundle/**/*
    - lib/generators/rspec/*/templates/**/*
    - tmp/**/*

Bundler/DuplicatedGem:
  Enabled: false

Gemspec/RequiredRubyVersion:
  # Rubocop checks that the target ruby version matches the gemspec version
  # but doesnt have a 2.2 option
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false

Layout/AssignmentIndentation:
  Enabled: false

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

# We use spaces, so it's less of a change to stick with that.
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Layout/SpaceAroundBlockParameters:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/AmbiguousOperator:
  Exclude:
    - Rakefile

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - features/step_definitions/additional_cli_steps.rb

Lint/AssignmentInCondition:
  Enabled: false

Lint/DuplicateMethods:
  Exclude:
    - example_app_generator/no_active_record/app/models/in_memory/model.rb

Lint/NonDeterministicRequireOrder:
  Exclude:
    - spec/spec_helper.rb

Lint/EmptyExpression:
  Enabled: false

Lint/ImplicitStringConcatenation:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

# Exceptions should be rescued with `Support::AllExceptionsExceptOnesWeMustNotRescue`
Lint/RescueException:
  Enabled: true

Lint/SuppressedException:
  Exclude:
    # RSpec is tightly coupled to capybara right now, this should be
    # re-evaluted in the future. For now we allow the empty rescue
    - lib/rspec/rails/vendor/capybara.rb
    - example_app_generator/generate_stuff.rb
    - example_app_generator/spec/support/default_preview_path

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# Warns when the class is excessively long.
Metrics/ClassLength:
  Max: 100

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

Metrics/ParameterLists:
  Exclude:
    - example_app_generator/spec/verify_custom_renderers_spec.rb

# Who cares what we call the argument for binary operator methods?
Naming/BinaryOperatorParameterName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/FileName:
  Exclude:
    # We break convention here so that when bundler requires the gem, which
    # uses the gem name, things work without user configuration.
    - lib/rspec-rails.rb

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

# We have too many special cases where we allow generator methods or prefer a
# prefixed predicate due to it's improved readability.
Naming/PredicateName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    reduce: 'inject'

Style/AccessModifierDeclarations:
  Enabled: false

# "Use alias_method instead of alias"
# We're fine with `alias`.
Style/Alias:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

# "Avoid the use of the case equality operator ==="
# We prefer using `Class#===` over `Object#is_a?` because `Class#===`
# is less likely to be monkey patched than `is_a?` on a user object.
Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/CommentedKeyword:
  Exclude:
    - spec/rspec/rails/example/view_example_group_spec.rb

Style/ConditionalAssignment:
  Enabled: false

Style/DateTime:
  Enabled: false

# We use YARD to enforce documentation. It works better than rubocop's
# enforcement...rubocop complains about the places we re-open
# `RSpec::Expectations` and `RSpec::Matchers` w/o having doc commments.
Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - spec/support/shared_examples.rb

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IdenticalConditionalBranches:
  Enabled: false

Style/IfUnlessModifierOfIfUnless:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NestedModifier:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - spec/rspec/rails/matchers/action_cable/have_stream_spec.rb

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Style/NumericPredicate:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()      # double-quoted string
    '%i': '[]'    # array of symbols
    '%q': ()      # single-quoted string
    '%Q': ()      # double-quoted string
    '%r': '{}'    # regular expression pattern
    '%s': ()      # a symbol
    '%w': '[]'    # array of single-quoted strings
    '%W': '[]'    # array of double-quoted strings
    '%x': ()      # a shell command as a string

Style/RaiseArgs:
  Exclude:
    - spec/rspec/rails/matchers/be_routable_spec.rb
    - spec/rspec/rails/matchers/have_rendered_spec.rb
    - spec/rspec/rails/matchers/redirect_to_spec.rb
    - spec/rspec/rails/matchers/route_to_spec.rb

Style/RegexpLiteral:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

# We haven't adopted the `fail` to signal exceptions vs `raise` for re-raises convention.
Style/SignalException:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - spec/rspec/rails/example/controller_example_group_spec.rb
    - spec/rspec/rails/matchers/active_job_spec.rb
    - spec/rspec/rails/matchers/be_a_new_spec.rb
    - spec/rspec/rails/matchers/has_spec.rb
    - spec/rspec/rails/matchers/have_enqueued_mail_spec.rb
    - spec/rspec/rails/matchers/have_rendered_spec.rb
    - spec/rspec/rails/setup_and_teardown_adapter_spec.rb

# This rule favors constant names from the English standard library which we don't load.
Style/SpecialGlobalVars:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StructInheritance:
  Enabled: false

# We don't care about single vs double qoutes.
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrivialAccessors:
  AllowDSLWriters: true
  AllowPredicates: true
  ExactNameMatch: true

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
