inherit_from: .rubocop_rspec_base.yml

# Over time we'd like to get this down, but this is what we're at now.
LineLength:
  Max: 186

# Over time we'd like to get this down, but this is what we're at now.
MethodLength:
  Max: 50

# We use spaces, so it's less of a change to stick with that.
SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

################################################################################
# Individual File Exclusions
################################################################################

AllCops:
  Exclude:
    # Templates are really ERB which Rubocop does not parse
    - 'lib/generators/rspec/*/templates/**/*'

FileName:
  Exclude:
    # We break convention here so that when bundler requires the gem, which
    # uses the gem name, things work without user configuration.
    - lib/rspec-rails.rb

HandleExceptions:
  Exclude:
    # RSpec is tightly coupled to capybara right now, this should be
    # re-evaluted in the future. For now we allow the empty rescue
    - lib/rspec/rails/vendor/capybara.rb

IfUnlessModifier:
  Exclude:
    # Allow single line statement as the style matches the remainder of the file
    - lib/rspec/rails/vendor/capybara.rb

PerlBackrefs:
  Exclude:
    # We probably can refactor the backref out, but for now excluding it since
    # we can't use named matches in 1.8.7
    - lib/generators/rspec/scaffold/scaffold_generator.rb
