# Over time we'd like to get this down, but this is what we're at now.
Metrics/CyclomaticComplexity:
  Max: 9 # default: 6

# Over time we'd like to get this down, but this is what we're at now.
Layout/LineLength:
  Max: 186 # default: 80

# Over time we'd like to get this down, but this is what we're at now.
Metrics/MethodLength:
  Max: 43 # default: 10

Metrics/ClassLength:
  Exclude:
    - lib/rspec/rails/matchers/have_enqueued_mail.rb
