# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rspec-rails}
  s.version = "2.0.0.a1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Chelimsky", "Chad Humphries"]
  s.date = %q{2010-01-22}
  s.description = %q{RSpec Rails}
  s.email = %q{dchelimsky@gmail.com;chad.humphries@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "example_app_template.rb",
     "lib/generators/rspec-rails.rb",
     "lib/generators/rspec-rails/controller/controller_generator.rb",
     "lib/generators/rspec-rails/controller/templates/controller_spec.rb",
     "lib/generators/rspec-rails/controller/templates/view_spec.rb",
     "lib/generators/rspec-rails/helper/helper_generator.rb",
     "lib/generators/rspec-rails/helper/templates/helper_spec.rb",
     "lib/generators/rspec-rails/install/install_generator.rb",
     "lib/generators/rspec-rails/install/templates/lib/tasks/rspec.rake",
     "lib/generators/rspec-rails/install/templates/script/autospec.tt",
     "lib/generators/rspec-rails/install/templates/script/spec.tt",
     "lib/generators/rspec-rails/install/templates/script/spec_server.tt",
     "lib/generators/rspec-rails/install/templates/spec/rcov.opts",
     "lib/generators/rspec-rails/install/templates/spec/spec.opts",
     "lib/generators/rspec-rails/install/templates/spec/spec_helper.rb",
     "lib/generators/rspec-rails/integration/integration_generator.rb",
     "lib/generators/rspec-rails/integration/templates/integration_spec.rb",
     "lib/generators/rspec-rails/mailer/mailer_generator.rb",
     "lib/generators/rspec-rails/mailer/templates/fixture",
     "lib/generators/rspec-rails/mailer/templates/mailer_spec.rb",
     "lib/generators/rspec-rails/model/model_generator.rb",
     "lib/generators/rspec-rails/model/templates/fixtures.yml",
     "lib/generators/rspec-rails/model/templates/model_spec.rb",
     "lib/generators/rspec-rails/observer/observer_generator.rb",
     "lib/generators/rspec-rails/observer/templates/observer_spec.rb",
     "lib/generators/rspec-rails/plugin/plugin_generator.rb",
     "lib/generators/rspec-rails/plugin/templates/%file_name%_spec.rb.tt",
     "lib/generators/rspec-rails/plugin/templates/test_helper.rb",
     "lib/generators/rspec-rails/scaffold/scaffold_generator.rb",
     "lib/generators/rspec-rails/scaffold/templates/controller_spec.rb",
     "lib/generators/rspec-rails/scaffold/templates/edit_spec.rb",
     "lib/generators/rspec-rails/scaffold/templates/index_spec.rb",
     "lib/generators/rspec-rails/scaffold/templates/new_spec.rb",
     "lib/generators/rspec-rails/scaffold/templates/routing_spec.rb",
     "lib/generators/rspec-rails/scaffold/templates/show_spec.rb",
     "lib/rspec/rails.rb",
     "lib/rspec/rails/example.rb",
     "lib/rspec/rails/example/controller_example_group.rb",
     "lib/rspec/rails/example/request_example_group.rb",
     "lib/rspec/rails/transactional_database_support.rb"
  ]
  s.homepage = %q{http://github.com/rspec/rspec-rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{RSpec for Rails}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, [">= 2.0.0.a1"])
      s.add_development_dependency(%q<cucumber>, [">= 0.5.3"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0.a1"])
      s.add_dependency(%q<cucumber>, [">= 0.5.3"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0.a1"])
    s.add_dependency(%q<cucumber>, [">= 0.5.3"])
  end
end
