#!/bin/bash
# This file is manually managed unlike the rest of core rspec gems because it is independent.

set -e
source script/functions.sh

bin/cucumber features/request_specs/request_spec.feature:31
