#!/bin/bash

set -ex

function check_documentation_coverage {
  bin/yard stats --list-undoc | ruby -e "
    while line = gets
      coverage ||= line[/([\d\.]+)% documented/, 1]
      puts line
    end

    unless Float(coverage) == 100
      puts \"\n\nMissing documentation coverage (currently at #{coverage}%)\"
      exit(1)
    end
  "
}

function documentation_enforced {
  if [ -x ./bin/yard ]; then
    return 0
  else
    return 1
  fi
}

bin/rake --trace

if documentation_enforced; then
  check_documentation_coverage
fi
