#!/bin/bash
# This file is manually managed unlike the rest of core rspec gems because it is independent.

set -e
source script/functions.sh

fold "binstub check" check_binstubs

fold "specs" run_specs_and_record_done

fold "acceptance" bin/rake acceptance --trace

fold "snippets" script/run_snippets.sh

if documentation_enforced; then
  fold "doc check" check_documentation_coverage
fi

fold "one-by-one specs" run_specs_one_by_one
