#!/bin/bash
# This file is manually managed unlike the rest of core rspec gems because it is independent.

set -e
source script/functions.sh

function check_style_and_lint {
  echo "bin/rubocop"
  eval "(unset RUBYOPT; rm -rf tmp/*; exec bin/rubocop)"
}

fold "rubocop" check_style_and_lint
