require 'rspec/rails/monkey'
require 'rspec/rails/extensions'
require 'rspec/rails/adapters'
require 'rspec/rails/transactional_database_support'
require 'rspec/rails/matchers'
require 'rspec/rails/example'
require 'rspec/rails/mocks'
