# System test configuration for Selenium container support.
# Generated by `rails generate rspec:install --selenium-container=<%= selenium_container %>`.
#
# Ensure this file is required in your rails_helper.rb by uncommenting:
#   Rails.root.glob('spec/support/**/*.rb').sort_by(&:to_s).each { |f| require f }

RSpec.configure do |config|
  config.before(type: :system) do
    if ENV["CAPYBARA_SERVER_PORT"]
      served_by host: "rails-app", port: ENV["CAPYBARA_SERVER_PORT"]

      driven_by :selenium, using: :headless_chrome, screen_size: [1400, 1400], options: {
        browser: :remote,
        url: "http://#{ENV.fetch("SELENIUM_HOST", "<%= selenium_container %>")}:4444"
      }
    else
      driven_by :selenium, using: :headless_chrome, screen_size: [1400, 1400]
    end
  end
end
