source 'http://rubygems.org'

gem 'arel', :path => "../../vendor/arel"
gem 'rails', :path => "../../vendor/rails"

gem 'sqlite3-ruby', :require => 'sqlite3'

group :development, :test do
  gem "rspec-rails",        :path => "../../../rspec-rails"
  gem "rspec",              :path => "../../../rspec"
  gem "rspec-core",         :path => "../../../rspec-core"
  gem "rspec-expectations", :path => "../../../rspec-expectations"
  gem "rspec-mocks",        :path => "../../../rspec-mocks"
  gem "rcov"
  gem "webrat"
  gem "autotest"
  gem "watchr"
end
