run('rspec spec -cfdoc') || abort
run('rake --trace spec') || abort
run('rake --trace spec:requests') || abort
run('rake --trace spec:models') || abort
run('rake --trace spec:views') || abort
run('rake --trace spec:controllers') || abort
run('rake --trace spec:helpers') || abort
run('rake --trace spec:mailers') || abort
run("rake --trace stats") || abort
