require 'spec_helper'
require 'generators/rspec/install/install_generator'

describe Rspec::Generators::InstallGenerator, :type => :generator do
  destination File.expand_path("../../../../../tmp", __FILE__)

  before { prepare_destination }

  it "generates .rspec" do
    run_generator
    expect(file('.rspec')).to exist
  end

  it "generates spec/spec_helper.rb" do
    run_generator
    expect(File.read( file('spec/spec_helper.rb') )).to match(
      / This file was generated by the `rails generate rspec:install` command./m
    )
  end

  context "generates spec/rails_helper.rb" do
    specify "requiring respec/rails" do
      run_generator
      expect(File.read( file('spec/rails_helper.rb') )).
        to match(/^require 'rspec\/rails'$/m)
    end

    case ::Rails::VERSION::STRING.to_f
    when 4.1
      specify "checking for maintaining the schema" do
        run_generator
        expect(File.read( file('spec/rails_helper.rb') )).
          to match(/ActiveRecord::Migration\.maintain_test_schema!/m)
      end
    when 4.0
      specify "checking for pending migrations" do
        run_generator
        expect(File.read( file('spec/rails_helper.rb') )).
          to match(/ActiveRecord::Migration\.check_pending!/m)
      end
    else
      specify "without a check for pending migrations" do
        run_generator
        expect(File.read( file('spec/rails_helper.rb') )).
          not_to match(/ActiveRecord::Migration\.check_pending!/m)
      end
    end
  end

  context "generates spec/rails_helper.rb", "without ActiveRecord available" do
    before do
      hide_const("ActiveRecord")
    end

    it "requires respec/rails" do
      run_generator
      expect(File.read( file('spec/rails_helper.rb') )).
        to match(/^require 'rspec\/rails'$/m)
    end

    it "does not include config.fixture_path" do
      run_generator
      expect(File.read( file('spec/rails_helper.rb') )).
        not_to match(/config\.fixture_path/m)
    end

    it "does not include config.use_transactional_fixtures" do
      run_generator
      expect(File.read( file('spec/rails_helper.rb') )).
        not_to match(/config\.use_transactional_fixtures/m)
    end

    case ::Rails::VERSION::STRING.to_f
      when 4.1
        it "does not check for maintaining test schema" do
          run_generator
          expect(File.read( file('spec/rails_helper.rb') )).
            not_to match(/ActiveRecord::Migration\.maintain_test_schema!/m)
        end
      when 4.0
        it "does not check for pending migrations" do
          run_generator
          expect(File.read( file('spec/rails_helper.rb') )).
            not_to match(/ActiveRecord::Migration\.check_pending!/m)
        end
    else
      it "does not check for pending migrations" do
        run_generator
        expect(File.read( file('spec/rails_helper.rb') )).
          not_to match(/ActiveRecord::Migration\.check_pending!/m)
      end
    end
  end

end
